create table public."Bills" (
  id text not null,
  created_at timestamp with time zone not null default now(),
  bill json null,
  updated_at timestamp without time zone null,
  constraint Bills_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Committees" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  committee json not null,
  updated_at timestamp without time zone null,
  membership_update timestamp without time zone null,
  leadership_update timestamp without time zone null,  
  constraint Committees_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Sponsors" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  sponsor json not null,
  updated_at timestamp without time zone null,
  info_update timestamp without time zone null,
  constraint Sponsors_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Update_schedules" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  next_update timestamp without time zone null,
  wait_time smallint null,
  constraint Update_schedules_pkey primary key (id),
  constraint Update_schedules_name_key unique (name)
) TABLESPACE pg_default;


create table public."Preferrences"(
  id uuid primary key default gen_random_uuid(),
  biennium text not null default '2025-26',
  bills jsonb not null default '[]' ::jsonb,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text unique,
  created_at timestamp with time zone not null default now()
) TABLESPACE pg_default;