create table public."Bills" (
  id text not null,
  created_at timestamp with time zone not null default now(),
  bill json null,
  updated_at timestamp without time zone null,
  constraint Bills_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Committees" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  committee json not null,
  updated_at timestamp without time zone null,
  constraint Committees_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Sponsors" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  sponsor json not null,
  updated_at timestamp without time zone null,
  constraint Sponsors_pkey primary key (id)
) TABLESPACE pg_default;